### ISSUE TITLE
Query too complex: running out of stack space

### ISSUE THREAD

**Issue by supersteves** [MonetDBSolutions/MonetDBe-Java#6]
So I thought I'd give Monetdbe-java a go, having a lot of experience using MonetDB and the JDBC driver. However I failed at the first hurdle, creating a table:

`CREATE TABLE "test" ("Category" VARCHAR(100), "Issue Date" TIMESTAMP, "Isin" VARCHAR(100), "Ticker" VARCHAR(100), "Issue Name" VARCHAR(100), "Is Snk" VARCHAR(100), "Coupon" DECIMAL, "Is Perpetual" VARCHAR(100), "Maturity Date" TIMESTAMP, "Tier" VARCHAR(100), "Benchmark Gilt" VARCHAR(100), "Composite Rating" VARCHAR(100), "Implied Credit Rating" VARCHAR(100), "Is Split" VARCHAR(100), "Liq Cat" DECIMAL, "Market Price" DECIMAL, "Market Yield" DECIMAL, "Model Yield" DECIMAL, "Market Spread (Govt)" DECIMAL, "Market Spread (Swaps)" DECIMAL)
`

I tried using disk and memory URLs. In both cases this resulted in:
`ParseException:SQLparser:42000!Query too complex: running out of stack space`.

Version 1.10

This was from one Java app. I tried another off the shelf app (SQuirreL) which crashed after a second of trying to connect (i.e. process disappeared). Mac OS X.

I don't think I'm doing anything unsupported.

**Comment by bernardom29** [comment]
Hi Steve,
Both of these errors are related to multi-threading issues. The production version of MonetDBe-Java does not support multiple threads sharing a Connection object. 

This limitation is one of the features of the next MonetDBe-Java release, which should be officially released over the next few weeks. If you want this feature earlier, you can use a development version. 
You can get it either through Maven:
```
<dependency>
  <groupId>monetdb</groupId>
  <artifactId>monetdbe-java</artifactId>
  <version>1.11-SNAPSHOT</version>
  <classifier>mac-fat</classifier>
</dependency>
```
Or you can download the jar manually:
https://oss.sonatype.org/service/local/repositories/snapshots/content/monetdb/monetdbe-java/1.11-SNAPSHOT/monetdbe-java-1.11-20220110.150446-16-mac-fat.jar

Try it and let us know if your issue is solved :)

**Comment by supersteves** [comment]
Ooh, sounds good. I'll give it another go! Thank you.
