### ISSUE TITLE
querytimeout throw an exception

### ISSUE THREAD

**Issue by 847880028** [MonetDBSolutions/MonetDBe-Java#7]
![image](https://user-images.githubusercontent.com/44664236/146292830-d98f6dcd-2b96-4e19-9543-d7ed770fe73e.png)
![image](https://user-images.githubusercontent.com/44664236/146292860-0ae6811f-eb9f-4ef4-b1cf-9302cc5b8645.png)
querytimeout Isn't the unit in milliseconds?Why does it throw an exception just after executing the query instead of 10 seconds later

**Comment by bernardom29** [comment]
Hi!
Query timeout is indeed in milliseconds, and it should only throw the exception 10 seconds after the start of the execution.
I could not reproduce this in my environment, but I'd need to know a bit more in order to debug it.

Could you give me some info about what OS you're using and if you're using maven to get the jar?
Thanks!

**Comment by 847880028** [comment]
OS：win10

you're using maven to get the jar? yes
```
<dependency>
    <groupId>monetdb</groupId>
    <artifactId>monetdbe-java</artifactId>
    <version>1.10</version>
</dependency>

**Comment by 847880028** [comment]
When I ran a query across about 4 million pieces of data, a single execution on Windows 10 would result in a JVM crash, but multiple executions on centos7 would result in almost no JVM crash

**Comment by bernardom29** [comment]
To figure out if this issue is solved by the new version, could you try to use the latest SNAPSHOT version for windows? 

Maven:
```
<dependency>
  <groupId>monetdb</groupId>
  <artifactId>monetdbe-java</artifactId>
  <version>1.11-SNAPSHOT</version>
  <classifier>windows</classifier>
</dependency>
```
Manual download:
https://oss.sonatype.org/service/local/repositories/snapshots/content/monetdb/monetdbe-java/1.11-SNAPSHOT/monetdbe-java-1.11-20220110.151548-17-windows.jar

**Comment by bernardom29** [comment]
Regarding the JVM crash, if this still happens with the new version, could you give me the core dump of the windows crash?
